/***************
 * DROP TABLES *
 ***************/

DROP TABLE PAYMENT;
DROP TABLE ORDERED_DRINK;
DROP TABLE ORDERS;
DROP TABLE DRINK;
DROP TABLE CLIENT_EMPLACEMENT;
DROP TABLE CLIENT;
DROP TABLE EMPLACEMENT;